disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Fadlan Abduh"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Going low-level."

["params.author"]
name = "Fadlan Abduh"
headline = "Make yourself at home, have a read."
bio = "Web dev gone deviant, chasing hardware truth."
